baseurl = "http://leckyyyyyyy.github.io/"
languageCode = "ja"
title = "leckyyyyyyy.info"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[permalinks]
  post = "/post/:year/:slug/"

[params]
  githubUrl = "https://github.com/leckyyyyyyy"
  twitterUrl = "https://twitter.com/leckyyyyyyy"
  GoogleAnalytics = "UA-62638779-1"
